spring:
  config:
    import: consul://, vault://
  couchbase:
    connection-string: ${COUCHBASE_URL}
    env:
      timeouts:
        query: 60000
  data:
    couchbase:
      auto-index: true
      bucket-name: services
  cloud:
    vault:
      fail-fast: true
      authentication: KUBERNETES
      application-name: ${spring.application.name}
      kubernetes:
        role: shaktiregistration
        kubernetes-path: kubernetes
        service-account-token-file: /var/run/secrets/kubernetes.io/serviceaccount/token
      uri: ${vault.host}
      namespace: admin
    consul:
      host: ${consul.host}
      port: ${consul.port}
      config:
        enabled: true
        failFast: true
        format: YAML
        data-key: data
        prefixes: apiServices
        default-context: ${spring.application.name}
        profile-separator: '/'
        acl-token: ${consul.token:root}
      discovery:
        instance-id: "${spring.application.name}:${random.int[1,999999]}"
        healthCheckInterval: 20s
        acl-token: ${consul.token:root}
        prefer-ip-address: true
    loadbalancer:
      ribbon:
        enabled: false
    stream:
      instanceIndex: ${KAFKA_CONSUMER_PARTITION_NO:0}
      instanceCount: ${KAFKA_CONSUMER_PARTITION_COUNT:1}
      function:
        definition: createUser;kycUserCreated;bountyReferralCreated;selfyIdCreated
      kafka:
        binder:
          brokers: ${kafka.bootstrap.servers:localhost:9092}
      bindings:
        createUser-out-0:
          destination: ${KAFKA_TOPIC_USER_CREATED:CREATE_USER}
          producer:
            partitioned: ${KAFKA_CONSUMER_PARTITION_ENABLED:false}
        kycUserCreated-in-0:
          destination: ${KAFKA_TOPIC_KYC_USER_CREATED:KYC_USER_CREATED}
          group: "${spring.application.name}-registration-state"
        bountyReferralCreated-in-0:
          destination: ${KAFKA_TOPIC_BOUNTY_CREATED:BOUNTY_CREATED}
          group: ${spring.application.name}
        selfyIdCreated-in-0:
          destination: ${KAFKA_TOPIC_SELFYID_CREATED:SELFYID_CREATED}
          group: ${spring.application.name}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${gluu.uri}
      client:
        provider:
          gluu:
            issuer-uri: ${gluu.uri}
        registration:
          gluu:
            client-id: ${gluu.client.id}
            client-secret: ${gluu.client.secret}
            authorization-grant-type: client_credentials
            scope: openid,permission
            provider: gluu

opentracing:
  jaeger:
    log-spans: true
    udp-sender.host: ${jaeger.host}
    udp-sender.port: ${jaeger.port}
    probabilistic-sampler:
      sampling-rate: 0.3

gluu:
  uri: https://iam-stg.shakticoin.com
  client:
    id: ${gluu.client.id}
    secret: ${gluu.client.secret}
  webclient:
    create-user-clientID: 1202.fc90a69c-4202-4fa7-906f-ae16d030d8a1
    create-user-jskpath: classpath:scim-rp_stg.jks
    create-user-jkspassword: 6rxExyQWyyiX
    create-user-client-keyID:

password:
  recovery:
    request:
      expires-in-minutes: 30
