user:
  registration:
    failed:
      cleanup-after: PT10M

spring:
  cloud:
    consul:
      discovery:
        health-check-critical-timeout: 5m
        health-check-path: /registration/api/v2/actuator/health
    discovery:
      client:
        composite-indicator:
          enabled: false
  application:
    name: shakti-registration
  webflux:
    base-path: /registration/api/v2
  jackson:
    default-property-inclusion: non_null

springdoc:
  api-docs:
    path: /api-docs

server:
  port: 8080
  shutdown: graceful

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    serviceregistry:
      enabled: false

  health:
    circuitbreakers:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    diskspace:
      enabled: false
    jms:
      enabled: false
    couchbase:
      enabled: false
    ping:
      enabled: false
    ldap:
      enabled: false
    mail:
      enabled: false
    binders:
      enabled: false
    refresh:
      enabled: false
    vault:
      enabled: false
    consul:
      enabled: false

logging:
  level:
    org.springframework.data.couchbase.repository.query: INFO
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN
    org.apache.kafka.clients.consumer.ProducerConfig: WARN

